# Generated by Django 5.1.4 on 2024-12-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='patient_details',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_hospital',
            field=models.CharField(default='Unknown Hospital', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
    ]
